import type { Metadata } from 'next'
import './globals.css'
import FeedProvider from '@/components/feedProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={'antialiased'}>
        <FeedProvider>{children}</FeedProvider>
      </body>
    </html>
  )
}
